"""Generate HMI screen-validation cases from the Overflow flow-data JSON.

One case per unique screen caption, grouped into HMI families by the screen-number prefix. Screen
validation is inherently per-screen and mechanical, so it is generated (uniform Given/When/Then,
title mirrors the screen name) rather than hand-written. Emits a push-ready YAML.

    python tools/gen_hmi_cases.py knowledge/flows/ETMoverflow_data.json proposals/etm-suite-restructure/hmi.cases.yaml
"""
from __future__ import annotations

import json
import re
import sys

import yaml

FAM = {"00": "Sign On", "01": "Sign On", "02": "Fare Look-Up", "03": "Promo Menu",
       "04": "Numeric Entry", "05": "Card Payment & Basket", "06": "Smartcards",
       "07": "Printer & Travel Mode", "08": "Driver Menu", "09": "Supervisor Menu",
       "10": "Technician Menu", "11": "Power Management", "12": "Barcodes"}
OVERFLOW = "https://overflow.io/s/NDLGF6NF/"


def family(cap: str) -> str | None:
    m = re.match(r"\s*(\d{1,2})[._]", cap)
    if m:
        return FAM.get(m.group(1).zfill(2), "Other")
    if cap.startswith(("PID/", "CardReader/", "COTD")):
        return "Displays, LEDs & PID"
    return None  # skip non-screen labels


def main(argv: list[str]) -> int:
    data = json.load(open(argv[1], encoding="utf-8"))
    caps: dict[str, None] = {}
    for p in data["pages"].values():
        for e in p.get("entities", {}).values():
            if e.get("type") == "screen":
                c = (e.get("caption") or "").strip()
                if c:
                    caps[c] = None
    fams: dict[str, list[str]] = {}
    for c in caps:
        f = family(c)
        if f:
            fams.setdefault(f, []).append(c)

    sections = []
    total = 0
    for fam in sorted(fams):
        cases = []
        for cap in sorted(fams[fam]):
            steps = (
                f'**Given** the ETM is in the state that presents the "{cap}" screen\n'
                f"**WHEN** the screen is displayed\n"
                f'**THEN** the screen matches the approved design for "{cap}"\n'
                f"**AND** all labels, options and on-screen indicators are present and correctly positioned"
            )
            cases.append({
                "title": f"Screen Validation — {cap}",
                "objective": f'This test is to confirm the "{cap}" screen matches the approved design.',
                "overflow": OVERFLOW,
                "steps": steps,
                "expected": f'The "{cap}" screen matches the approved Overflow design with all elements present.',
            })
            total += 1
        sections.append({"path": f"HMI Screen Validation / {fam}", "cases": cases})

    doc = {"suite_id": 30254,
           "defaults": {"template_id": 1, "custom_autoconfirmation": False,
                        "custom_devtypes": [25], "custom_revstatus": 2},
           "sections": sections}
    with open(argv[2], "w", encoding="utf-8") as fh:
        fh.write("# ETM — HMI Screen Validation (generated by tools/gen_hmi_cases.py).\n"
                 "# One case per unique Overflow screen, grouped by family. Titles mirror the exact\n"
                 "# screen name (advisory title findings are expected and intentional, as for POS).\n")
        yaml.safe_dump(doc, fh, sort_keys=False, allow_unicode=True, width=4096, default_flow_style=False)
    print(f"wrote {argv[2]}: {len(sections)} families, {total} screen-validation cases")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
