"""Generate PV HMI screen-validation cases from the PV UX image folders.

No Overflow JSON for PV, so screens come from the exported image filenames. One case per unique
screen, grouped into HMI families. File-based + Write-tool output (clean UTF-8).
"""
from __future__ import annotations
import re
from pathlib import Path
import yaml

ROOT = Path("knowledge/flows/pv")
FOLDERS = {
    "Validation Screens": "Translink Validators 3.1.7 - Platform Validator-Barcode",
    "Technician Menu": "Translink Validators 3.1.7 - Technician Menu - Platform Validator",
}
OUT = "proposals/pv-suite-restructure/hmi.cases.yaml"


def screens(folder: Path) -> list[str]:
    seen: dict[str, None] = {}
    for f in sorted(folder.glob("*.png")):
        n = f.stem
        if n.lower().startswith("screenshot"):
            continue
        n = re.sub(r" \(\d+\)$", "", n)  # drop dup marker
        seen[n] = None
    return list(seen)


def main() -> int:
    sections = []
    total = 0
    for fam, folder in FOLDERS.items():
        cases = []
        for s in screens(ROOT / folder):
            cases.append({
                "title": f"Screen Validation — {s}",
                "objective": f'This test is to confirm the "{s}" screen matches the approved design.',
                "attach": f"knowledge/flows/pv/{folder}/{s}.png",
                "steps": (
                    f'**Given** the PV is in the state that presents the "{s}" screen\n'
                    f"**WHEN** the screen is displayed\n"
                    f'**THEN** the screen matches the approved design for "{s}"\n'
                    f"**AND** all labels, icons and on-screen indicators are present and correctly positioned"
                ),
                "expected": f'The "{s}" screen matches the approved design with all elements present.',
            })
            total += 1
        sections.append({"path": f"HMI Screen Validation / {fam}", "cases": cases})
    doc = {"suite_id": 30255,
           "defaults": {"template_id": 1, "custom_autoconfirmation": False,
                        "custom_devtypes": [10], "custom_revstatus": 2},
           "sections": sections}
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("# PV — HMI Screen Validation (generated by tools/gen_pv_hmi.py from the PV UX image folders).\n")
        yaml.safe_dump(doc, fh, sort_keys=False, allow_unicode=True, width=4096)
    print(f"wrote {OUT}: {total} screen cases across {len(sections)} families")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
