*** Settings ***
Documentation    Advance ticket date-entry screen.
...
...              Screen: `advancedatelayout.xml`. Static labels confirmed:
...              - `AdvanceTicket.title` ("Advance Ticket")
...              - `AdvanceTicket.label_input_date` ("Set Date:")
...              - `AdvanceTicket.hint_input_date` ("DD/MM/YY")
...              - `AdvanceTicket.select_date` ("Select date of travel:")
Resource         ${CURDIR}/../../../../resources/common.resource
Suite Setup      Connect To Device
Suite Teardown   Disconnect From Device
Test Setup       Clear Device Logs
Test Teardown    Collect Test Artefacts
Force Tags       project:translink    device_types:POS    feature:transactions

*** Variables ***
${DEVICE_TYPES}    POS
@{ADVANCE_TICKET_LABELS}    AdvanceTicket.title    AdvanceTicket.label_input_date    AdvanceTicket.select_date

*** Test Cases ***
Advance Ticket Screen Renders
    [Documentation]    TODO: route into the advance-ticket flow (likely menu -> Advance Ticket).
    Start Activity    com.flowbird.pos
    Assert Visible Labels    @{ADVANCE_TICKET_LABELS}    screen=advance-ticket screen

Advance Ticket Accepts Future Date
    [Documentation]    Entering a valid future date in DD/MM/YY format should
    ...    be accepted. TODO: figure out which control receives the text
    ...    input. The hint is set on a TextView/EditText in
    ...    `advancedatelayout.xml` -- the resource id is auto-generated by
    ...    Xamarin so find-by-text(hint) is our best handle.
    Start Activity    com.flowbird.pos
    ${hint}=      Lookup POS String    AdvanceTicket.hint_input_date
    ${shell}=     Get Android Shell
    ${centre}=    Call Method    ${shell}    find_by_text    ${hint}    exact=${False}
    Skip If    $centre is None
    ...    Advance-ticket date input not located by hint '${hint}'; the Xamarin layout may render the hint inside a sub-view we can't tap.
    Call Method    ${shell}    tap    ${centre}[0]    ${centre}[1]
    Input Text    31/12/30
    # TODO: assert the date was accepted (could check the visible input value
    # via uiautomator dump once we know the parent View's text attribute).
