version: 1
targets:
- project: Translink
  device: POS
  old_suite: AA-POS Acceptance Test
  old_suite_id: 9317
  new_suite: GG - POS - Claude Suite
  new_suite_id: 30253
  fresh_build: false
  testrail_project_id: 42
  new_testrail_project_id: 42
- project: Translink
  device: ETM
  old_suite: AA-ETM-Acceptance Test
  old_suite_id: 4943
  new_suite: NEW ETM-Acceptance Suite
  new_suite_id: 30254
  fresh_build: false
  testrail_project_id: 42
  new_testrail_project_id: 42
- project: Translink
  device: GV
  old_suite: AA - Gate Validator - Acceptance Test
  old_suite_id: 14973
  new_suite: NEW GV Test Suite
  new_suite_id: 30286
  fresh_build: false
  testrail_project_id: 42
  new_testrail_project_id: 42
- project: Translink
  device: TVM
  old_suite: AA-TVM-Acceptance Test-V03
  old_suite_id: 5602
  new_suite: NEW TVM Test Suite
  new_suite_id: 30284
  fresh_build: false
  testrail_project_id: 42
  new_testrail_project_id: 42
- project: Translink
  device: HHD
  old_suite: AA-HHD-Acceptance
  old_suite_id: 5446
  new_suite: NEW HHD Test Suite
  new_suite_id: 30285
  fresh_build: false
  testrail_project_id: 42
  new_testrail_project_id: 42
- project: Translink
  device: PV
  old_suite: AA-Platform Validator Acceptance Test
  old_suite_id: 10047
  new_suite: NEW PV-Acceptance Test Suite
  new_suite_id: 30255
  fresh_build: false
  testrail_project_id: 42
  new_testrail_project_id: 42
- project: Translink
  device: BOS
  old_suite: 2.1-Backoffice Systems - Acceptance Suite
  old_suite_id: 14441
  new_suite: NEW BOS & ABT Suite
  new_suite_id: 30279
  fresh_build: false
  testrail_project_id: 42
  new_testrail_project_id: 42
- project: NJT
  device: ETM
  old_suite: NJT Farebox and Register Replacement
  old_suite_id: 30169
  new_suite: NJT - SystemTestOps2
  new_suite_id: 30462
  fresh_build: false
  testrail_project_id: 27
  new_testrail_project_id: null
