"""Extract flow annotations + screen captions from an Overflow flow-data JSON export.

Overflow share links are JS shells (WebFetch can't read them); the real data is the JSON the app
fetches, grabbed from the browser Network tab. This turns that JSON into a human-readable Markdown
checklist of flows -> screens -> annotation notes, used to ground gherkin-author/coverage-analyst.

Usage:
    python tools/extract_overflow_annotations.py <input.json> <output.md>

Schema (target v11/v12): top-level `pages` = flows; each page has `title` and `entities`
(dict of <type><uuid> -> obj). Entity `type` in {screen, label, link, shape, image}. `screen.caption`
= the screen name; `label.text` = an annotation note placed on the canvas.
"""
from __future__ import annotations

import json
import sys
from collections import OrderedDict


def _clean(s: str | None) -> str:
    return (s or "").replace("\r", "").strip()


def extract(data: dict) -> "OrderedDict[str, dict]":
    pages = data.get("pages", {})
    # order pages by their 'order' field (string), fallback to insertion order
    ordered = sorted(pages.items(), key=lambda kv: float(kv[1].get("order", 0) or 0))
    out: "OrderedDict[str, dict]" = OrderedDict()
    for _pid, page in ordered:
        title = _clean(page.get("title")) or "(untitled board)"
        screens: list[str] = []
        notes: list[str] = []
        for ent in page.get("entities", {}).values():
            etype = ent.get("type")
            if etype == "screen":
                cap = _clean(ent.get("caption"))
                if cap:
                    screens.append(cap)
            elif etype == "label":
                txt = _clean(ent.get("text"))
                if txt:
                    notes.append(txt)
        # dedupe preserving order
        out[title] = {
            "screens": list(dict.fromkeys(screens)),
            "notes": list(dict.fromkeys(notes)),
        }
    return out


def render(flows: "OrderedDict[str, dict]", src: str) -> str:
    lines = [
        f"# Overflow flow annotations — extracted from `{src}`",
        "",
        "Auto-generated by `tools/extract_overflow_annotations.py`. Each flow lists its screen names "
        "and the annotation notes placed on the canvas. These are the **design behaviour spec** "
        "(preconditions, thresholds, printout contents, error handling) — a grounding source for "
        "case authoring + a coverage checklist. Do not hand-edit; re-run the extractor.",
        "",
    ]
    total_notes = 0
    for title, body in flows.items():
        notes = body["notes"]
        screens = body["screens"]
        total_notes += len(notes)
        lines.append(f"## {title}")
        lines.append(f"*{len(screens)} screens · {len(notes)} annotation notes*")
        lines.append("")
        if screens:
            lines.append("**Screens:** " + " · ".join(screens))
            lines.append("")
        if notes:
            lines.append("**Annotations:**")
            for n in notes:
                # collapse internal newlines into a single note bullet
                flat = " / ".join(p.strip() for p in n.split("\n") if p.strip())
                lines.append(f"- {flat}")
            lines.append("")
    lines.insert(
        4,
        f"**{len(flows)} flows · {total_notes} annotation notes total.**\n",
    )
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(__doc__)
        return 2
    inp, outp = argv[1], argv[2]
    with open(inp, encoding="utf-8") as fh:
        data = json.load(fh)
    flows = extract(data)
    md = render(flows, inp.replace("\\", "/").split("/")[-1])
    with open(outp, "w", encoding="utf-8") as fh:
        fh.write(md)
    print(f"wrote {outp}: {len(flows)} flows, "
          f"{sum(len(b['notes']) for b in flows.values())} notes, "
          f"{sum(len(b['screens']) for b in flows.values())} screens")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
